import { KickEgWave, KickParametersSuit } from "@/base/parameters";

export enum KickPresetKey {
  kick1,
  kick2,
  kick3,
  kick4,
  kick5,
}

export const kickPresets = {
  [KickPresetKey.kick1]: {
    oscWaveNoise: false,
    oscShape: 0.3,
    oscPitch: 0.44,
    pitchEgWave: KickEgWave.ds,
    pitchEgTime: 0.3,
    pitchEgShape: 0,
    pitchEgAmount: 0.53,
    ampEgWave: KickEgWave.d,
    ampEgTime: 0.63,
    ampEgShape: 0.6,
    ampDrive: 0.05,
    volume: 0.66,
  },
  [KickPresetKey.kick2]: {
    oscWaveNoise: false,
    oscShape: 0.5,
    oscPitch: 0.32,
    pitchEgWave: KickEgWave.ds,
    pitchEgTime: 0.23,
    pitchEgShape: 0.21,
    pitchEgAmount: 0.74,
    ampEgWave: KickEgWave.d,
    ampEgTime: 0.52,
    ampEgShape: 0.38,
    ampDrive: 0.28,
    volume: 1,
  },
  [KickPresetKey.kick3]: {
    oscWaveNoise: false,
    oscShape: 0.61,
    oscPitch: 0.34,
    pitchEgWave: KickEgWave.ds,
    pitchEgTime: 0.26,
    pitchEgShape: 0.12,
    pitchEgAmount: 0.74,
    ampEgWave: KickEgWave.hd,
    ampEgTime: 0.41,
    ampEgShape: 0.39,
    ampDrive: 0,
    volume: 0.61,
  },
  [KickPresetKey.kick4]: {
    oscWaveNoise: false,
    oscShape: 0.32,
    oscPitch: 0.32,
    pitchEgWave: KickEgWave.ds,
    pitchEgTime: 0.29,
    pitchEgShape: 0.23,
    pitchEgAmount: 0.68,
    ampEgWave: KickEgWave.hd,
    ampEgTime: 0.55,
    ampEgShape: 0.51,
    ampDrive: 0,
    volume: 0.46,
  },
  [KickPresetKey.kick5]: {
    oscWaveNoise: false,
    oscShape: 0.78,
    oscPitch: 0.34,
    pitchEgWave: KickEgWave.ds,
    pitchEgTime: 0.42,
    pitchEgShape: 0.07,
    pitchEgAmount: 0.73,
    ampEgWave: KickEgWave.d,
    ampEgTime: 0.6,
    ampEgShape: 0.38,
    ampDrive: 0.21,
    volume: 0.24,
  },
} satisfies Record<KickPresetKey, KickParametersSuit>;
